### ISSUE TITLE
TreeModel needs refactor

### ISSUE THREAD

**Issue by fundies** [enigma-dev/RadialGM#139]
The tree model should refactored to inherit from the other models (particularly RepeadedMessageModel)

**Comment by RobertBColton** [comment]
I gave this an attempt and it didn't work out. There's a couple of problems, first, the tree model isn't really a _repeated_ message model, it's a _recursive_ message model which we don't have any other abstraction for. This kind of goes back to #20 where I was originally proposing a giant 3D recursive single instance model for the entire editor. Just changing the inheritance to do this creates this problem of calling the parent constructor of `RepeatedMessageModel` which expects a repeated field, which is child, but would ignore that it's actually recursive.

There were some other small issues too, like the fact that all of our repeated proto models have the "owner" typed to be other proto models instead of `QObject` like `ProtoModel` does and thus they can't be parented to widgets or the application main window. This small issue we could consider to be intentional though so that only a single root model is owned by the application, and the rest are all still owned by other models. If we do that though then it is the `TreeModel` who must restrict itself to only being owned by another model and change its constructor.

**Comment by RobertBColton** [comment]
Closing as resolved by #144 super duper model.

**Comment by RobertBColton** [comment]
Closing as resolved by Josh in #201.
